name: pyar_pairprogramming
channels:
        - conda-forge
        - defaults
dependencies:
        - rise
        - jupyter-server-proxy
        - code-server
        - jupyter-vscode-proxy
        - pytest
        - jupyterlab
        - ipywidgets
        - voila
        - nodejs
        - pip
        - pip:
            - nbval
            - pytest-cov
            - radon
            - rope
