#!/bin/bash -l

set -ex

export SERVICE_URL=https://open-vsx.org/vscode/gallery
export ITEM_URL=https://open-vsx.org/vscode/item

code-server --install-extension ms-python.python
code-server --install-extension gitduck.code-streaming
code-server --install-extension vscodevim.vim
